const CustomerDetails = require("../../models/chamath/customerDetails");
const puppeteer = require("puppeteer");
const path = require('path');

// Function to generate the PDF report
const customerReport = async (req, res) => {
    try {
        // Fetching the inquiry details
        const customer = await CustomerDetails.find({});

        // Launching the browser
        const browser = await puppeteer.launch();
        const page = await browser.newPage();

        const filePath = path.resolve(__dirname, '../../../', 'customerReport.pdf');

        // Setting the content of the PDF with the updated logo and heading format
        await page.setContent(`
            <html>
                <head>
                    <style>
                        body {
                            font-family: 'Calibri', sans-serif;
                            margin: 0;
                            padding: 0;
                            font-size: 12px;
                        }
                        .header {
                            text-align: center;
                            margin-bottom: 10px;
                            font-size: 40px;
                            display: flex;
                            align-items: center;
                            justify-content: center;
                        }
                        .header img {
                            height: 120px;
                            width: 120px;
                            margin-right: 10px;
                        }
                        .company-details {
                            text-align: center;
                            font-size: 14px;
                            margin-bottom: 10px;
                        }
                        hr {
                            border: 1px solid #4CAF50;
                            margin: 20px 0;
                        }
                        table {
                            width: 100%;
                            border-collapse: collapse;
                            margin-bottom: 20px;
                        }
                        th, td {
                            border: 1px solid #dddddd;
                            text-align: left;
                            padding: 8px;
                        }
                        th {
                            background-color: #f2f2f2;
                            font-weight: bold;
                        }
                        tr:nth-child(even) {
                            background-color: #f9f9f9;
                        }
                        .footer {
                            text-align: center;
                            font-size: 10px;
                            margin-top: 20px;
                        }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <img src="http://localhost:5000/assets/logo.png" alt="Company Logo" />
                        <b>Smart-Dispose Pvt. Ltd.</b>
                    </div>
                    <div class="company-details">
                        <b>Address: No. 123, Main Street, Colombo, Sri Lanka</b>
                    </div>
                    <div class="company-details">
                        <b>Telephone: +94 11 2345678</b>
                    </div>
                    <hr />
                    <h1 style="text-align: center; color: #4CAF50;">Customer List</h1>
                    <table>
                        <tr>
                            <th>Customer Name</th>
                            <th>Email</th>
                            <th>Contact No.</th>
                            <th>Location</th>
                        </tr>
                        ${customer.map(customer => `
                            <tr>
                                <td>${customer.cusFname} ${customer.cusLname}</td>
                                <td>${customer.cusMail}</td>
                                <td>${customer.pNum}</td>
                                <td>${customer.cusAddr}</td>
                            </tr>
                        `).join('')}
                    </table>
                    <div class="footer">
                        <p>Generated by Smart-Dispose</p>
                    </div>
                </body>
            </html>
        `);

        // Generating the PDF
        await page.pdf({
            path: filePath,
            format: 'A4',
            margin: {
                top: "1cm",
                bottom: "1cm",
                left: "1cm",
                right: "1cm"
            }
        });

        await browser.close();
        res.sendFile(filePath);
        
    } catch (error) {
        res.status(500).send('Error generating PDF');
    }
}

module.exports = customerReport;